services:
  jellyfin:
    image: jellyfin/jellyfin
    container_name: jellyfin
    user: UID:GID
    network_mode: 'host'
    volumes:
      - /home/jellyfin/docker/jellyfincfg:/config
      - /home/jellyfin/docker/cache:/cache
      - type: bind
        source: /home/jellyfin/docker/media
        target: /media
      - type: bind
        source: /home/jellyfin/docker/media2
        target: /media2
        read_only: true
    restart: 'unless-stopped'
    environment:
      - JELLYFIN_PublishedServerUrl=http://example.com
    extra_hosts:
      - 'host.docker.internal:host-gateway'

  deluge:
    image: lscr.io/linuxserver/deluge:latest
    container_name: deluge
    user: UID:GID
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
      - DELUGE_LOGLEVEL=error 
    volumes:
      - /home/jellyfin/docker/delugecfg:/config
      - /home/jellyfin/docker/media:/downloads
    ports:
      - 8112:8112
      - 6881:6881
      - 6881:6881/udp
      - 58846:58846 
    restart: unless-stopped
